# Generated by Django 3.2.13 on 2022-05-17 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.Field(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter product name', max_length=20)),
                ('image', models.ImageField(upload_to='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('situacao', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.Field(primary_key=True, serialize=False)),
                ('cpf', models.CharField(max_length=14)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=30)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.IntegerField()),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projeto.product')),
            ],
        ),
    ]
