# Generated by Django 3.2.13 on 2022-05-18 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='id_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projeto.product', verbose_name='Produto'),
        ),
    ]
