# Generated by Django 3.2.13 on 2022-05-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0004_alter_sell_id_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
