# Generated by Django 3.2.13 on 2022-05-18 19:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0005_alter_sell_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 18, 16, 56, 53, 113036)),
        ),
    ]
