# Generated by Django 3.2.13 on 2022-05-19 16:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0006_alter_sell_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 19, 13, 52, 12, 412890)),
        ),
    ]
